
### jekyll settings
baseurl: ""

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "projects"
    values:
      layout: projeto
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: noticia



collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

permalink: /:title/


# jekyll theme
theme: null

sass:
  sass_dir: assets/css

# force jekyll to include certain files/folders
include:
  - assets/css
  - assets/js

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
